@base = http://localhost:3000/api/v1
@json = application/json
@currency = ARS
@amount = 1000
@alice = alice
@bob = bob
@idem = {{$guid}}  # idempotency key dinámico por request

### Health (endpoint demo de Nest, fuera de /api/v1) — opcional
GET http://localhost:3000/api
Accept: {{json}}


### Crear usuario Alice
# @name createAlice
POST {{base}}/wallet/users
Content-Type: {{json}}

{
  "userId": "{{alice}}"
}


### Crear usuario Bob
# @name createBob
POST {{base}}/wallet/users
Content-Type: {{json}}

{
  "userId": "{{bob}}"
}


### Listar usuarios
# @name listUsers
GET {{base}}/wallet/users
Accept: {{json}}


### Top-up a Alice
# @name topupAlice
POST {{base}}/wallet/topup
Content-Type: {{json}}
Idempotency-Key: {{idem}}

{
  "userId": "{{alice}}",
  "amount": {{amount}},
  "currency": "{{currency}}"
}


### Transferir de Alice -> Bob
# @name transferAtoB
POST {{base}}/wallet/transfer
Content-Type: {{json}}
Idempotency-Key: {{idem}}

{
  "fromUserId": "{{alice}}",
  "toUserId": "{{bob}}",
  "amount": 250,
  "currency": "{{currency}}"
}


### Balance puntual de Alice en {{currency}}
# @name balanceAlice
GET {{base}}/wallet/balance/{{alice}}/{{currency}}
Accept: {{json}}


### Balances de Alice (todas las monedas)
# @name balancesAlice
GET {{base}}/wallet/balances/{{alice}}
Accept: {{json}}


### Extracto de Alice (últimos 12 movimientos) en {{currency}}
# @name statementAlice
GET {{base}}/wallet/statement/{{alice}}/{{currency}}?limit=12
Accept: {{json}}


### (opcional) Repetir Top-up con la MISMA llave de idempotencia (no debe duplicar)
# @idem = 11111111-1111-1111-1111-111111111111
POST {{base}}/wallet/topup
Content-Type: {{json}}
Idempotency-Key: {{idem}}

{
  "userId": "{{alice}}",
  "amount": {{amount}},
  "currency": "{{currency}}"
}
